/*
Rogatia NNUE trainer config -- the Phase 8 data retrain.

    (768 -> 256)x2 -> 1, SCReLU, QA=255, QB=64, eval scale 400

Derived from bullet's own examples/simple.rs, which is already this exact
architecture; the changes are the hidden size, the data loader pointing at our
datagen output, and a schedule sized to the data we actually have.

This file is the authoritative copy.  bullet declares its examples explicitly
in crates/bullet_lib/Cargo.toml, so rather than editing the clone's manifest we
copy over the example it already declares:

    cp trainer/rogatia.rs ~/bullet/examples/simple.rs
    cd ~/bullet && CUDA_PATH=/opt/cuda LD_LIBRARY_PATH=/opt/cuda/lib64 \
        cargo r -r --package bullet_lib --features cuda --example simple

Output lands in ~/bullet/checkpoints/<net_id>-<superbatch>/.
*/
use bullet_lib::{
    game::inputs::Chess768,
    nn::optimiser::AdamW,
    trainer::{
        save::SavedFormat,
        schedule::{TrainingSchedule, TrainingSteps, lr, wdl},
        settings::LocalSettings,
    },
    value::{ValueTrainerBuilder, loader},
};

// STILL 256, deliberately.  The roadmap's Phase 8 raises this to 1024 with
// output buckets, but that is a second experiment.  This run changes the DATA
// only -- a corpus generated by a ~3175 engine instead of the ~2800 PSQT one,
// deduplicated and thinned -- so a net-vs-net SPRT on identical code measures
// the data and nothing else.  Scale the architecture after that number is in.
const HIDDEN_SIZE: usize = 256;
const SCALE: i32 = 400;
const QA: i16 = 255;
const QB: i16 = 64;

// One superbatch is one pass over the data, so this is set from the dataset
// size rather than left at bullet's 6104 (which assumes exactly 100M).
const BATCH_SIZE: usize = 16_384;
const POSITIONS: usize = 160_000_000;   // scripts/filter.cpp output

fn main() {
    let mut trainer = ValueTrainerBuilder::default()
        .dual_perspective()
        .optimiser(AdamW)
        .inputs(Chess768)
        // The order here is the order the engine's loader reads them in.
        .save_format(&[
            SavedFormat::id("l0w").round().quantise::<i16>(QA),
            SavedFormat::id("l0b").round().quantise::<i16>(QA),
            SavedFormat::id("l1w").round().quantise::<i16>(QB),
            SavedFormat::id("l1b").round().quantise::<i16>(QA * QB),
        ])
        .loss_fn(|output, target| output.sigmoid().squared_error(target))
        .build(|builder, stm_inputs, ntm_inputs| {
            let l0 = builder.new_affine("l0", 768, HIDDEN_SIZE);
            let l1 = builder.new_affine("l1", 2 * HIDDEN_SIZE, 1);

            let stm_hidden = l0.forward(stm_inputs).screlu();
            let ntm_hidden = l0.forward(ntm_inputs).screlu();
            l1.forward(stm_hidden.concat(ntm_hidden))
        });

    let schedule = TrainingSchedule {
        net_id: "rogatia-p8a".to_string(),
        eval_scale: SCALE as f32,
        steps: TrainingSteps {
            batch_size: BATCH_SIZE,
            batches_per_superbatch: POSITIONS / BATCH_SIZE,
            start_superbatch: 1,
            end_superbatch: 40,
        },
        // 0.3 = 30% game result, 70% search score.  bullet's example uses 0.75,
        // which fits mostly outcomes and pushes the net toward saturated evals
        // -- the scaffold net came out roughly twice the scale of the search
        // scores.  That matters here because Phase 4's pruning margins (RFP
        // 75/ply, the SEE thresholds) are calibrated to the old eval's scale,
        // and an inflated eval silently makes all of them more aggressive.
        wdl_scheduler: wdl::ConstantWDL { value: 0.3 },
        lr_scheduler: lr::StepLR { start: 0.001, gamma: 0.3, step: 15 },
        save_rate: 10,
    };

    let settings = LocalSettings {
        threads: 4,
        test_set: None,
        output_directory: "checkpoints",
        batch_queue_size: 64,
    };

    // One shard: scripts/filter.cpp merges the 16 datagen shards, drops the
    // poisoned labels and the duplicate positions, and thins the rest.  Do NOT
    // point this at data/20260728-090808/*.bin -- that is the raw corpus, and
    // 3.8% of it is duplicate positions.
    let data_loader = loader::DirectSequentialDataLoader::new(&["data/filtered-p8.bin"]);

    trainer.run(&schedule, &settings, &data_loader);
}
